#!/bin/sh

# some of these directories may not exist until submodules have been
# initialized - just keep going & clean anything that needs cleaning

if cd deps/luv ; then
  [ -f Makefile ] && make clean
  cd ../..
fi

if cd deps/luajit 2>/dev/null ; then
  make clean
  cd ../..
fi

if cd deps/sqlite ; then
  rm -rf build
  # for some reason the out-of-tree build still modifies this...
  git checkout .
  # ...and creates/leaves this directory behind
  rm -rf autom4te.cache
  cd ../..
fi

rm -f deps/luautf8/lutf8lib.o

if cd deps/lpeg ; then
  make clean
  cd ../..
fi

#cd nano
#rm -rf build
#mkdir build
#cd ..

rm -rf build/*

