# CMake generated Testfile for 
# Source directory: /Users/atman/code/pylon/nng/tests
# Build directory: /Users/atman/code/pylon/nng/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(convey_test "/Users/atman/code/pylon/nng/tests/convey_test" "-v" "-d" "-p" "ENV_TEST=ON" "-p" "ANOTHERNAME" "-p" "AGAIN=yes" "extra")
set_tests_properties(convey_test PROPERTIES  TIMEOUT "2")
add_test(aio "/Users/atman/code/pylon/nng/tests/aio" "-v" "-p" "TEST_PORT=12100")
set_tests_properties(aio PROPERTIES  TIMEOUT "5")
add_test(bufsz "/Users/atman/code/pylon/nng/tests/bufsz" "-v" "-p" "TEST_PORT=12120")
set_tests_properties(bufsz PROPERTIES  TIMEOUT "5")
add_test(base64 "/Users/atman/code/pylon/nng/tests/base64" "-v" "-p" "TEST_PORT=12140")
set_tests_properties(base64 PROPERTIES  TIMEOUT "5")
add_test(device "/Users/atman/code/pylon/nng/tests/device" "-v" "-p" "TEST_PORT=12160")
set_tests_properties(device PROPERTIES  TIMEOUT "5")
add_test(errors "/Users/atman/code/pylon/nng/tests/errors" "-v" "-p" "TEST_PORT=12180")
set_tests_properties(errors PROPERTIES  TIMEOUT "2")
add_test(files "/Users/atman/code/pylon/nng/tests/files" "-v" "-p" "TEST_PORT=12200")
set_tests_properties(files PROPERTIES  TIMEOUT "5")
add_test(httpclient "/Users/atman/code/pylon/nng/tests/httpclient" "-v" "-p" "TEST_PORT=12220")
set_tests_properties(httpclient PROPERTIES  TIMEOUT "60")
add_test(httpserver "/Users/atman/code/pylon/nng/tests/httpserver" "-v" "-p" "TEST_PORT=12240")
set_tests_properties(httpserver PROPERTIES  TIMEOUT "30")
add_test(idhash "/Users/atman/code/pylon/nng/tests/idhash" "-v" "-p" "TEST_PORT=12260")
set_tests_properties(idhash PROPERTIES  TIMEOUT "5")
add_test(inproc "/Users/atman/code/pylon/nng/tests/inproc" "-v" "-p" "TEST_PORT=12280")
set_tests_properties(inproc PROPERTIES  TIMEOUT "5")
add_test(ipc "/Users/atman/code/pylon/nng/tests/ipc" "-v" "-p" "TEST_PORT=12300")
set_tests_properties(ipc PROPERTIES  TIMEOUT "5")
add_test(ipcperms "/Users/atman/code/pylon/nng/tests/ipcperms" "-v" "-p" "TEST_PORT=12320")
set_tests_properties(ipcperms PROPERTIES  TIMEOUT "5")
add_test(ipcwinsec "/Users/atman/code/pylon/nng/tests/ipcwinsec" "-v" "-p" "TEST_PORT=12340")
set_tests_properties(ipcwinsec PROPERTIES  TIMEOUT "5")
add_test(list "/Users/atman/code/pylon/nng/tests/list" "-v" "-p" "TEST_PORT=12360")
set_tests_properties(list PROPERTIES  TIMEOUT "5")
add_test(message "/Users/atman/code/pylon/nng/tests/message" "-v" "-p" "TEST_PORT=12380")
set_tests_properties(message PROPERTIES  TIMEOUT "5")
add_test(multistress "/Users/atman/code/pylon/nng/tests/multistress" "-v" "-p" "TEST_PORT=12400")
set_tests_properties(multistress PROPERTIES  TIMEOUT "60")
add_test(nonblock "/Users/atman/code/pylon/nng/tests/nonblock" "-v" "-p" "TEST_PORT=12420")
set_tests_properties(nonblock PROPERTIES  TIMEOUT "60")
add_test(options "/Users/atman/code/pylon/nng/tests/options" "-v" "-p" "TEST_PORT=12440")
set_tests_properties(options PROPERTIES  TIMEOUT "5")
add_test(pipe "/Users/atman/code/pylon/nng/tests/pipe" "-v" "-p" "TEST_PORT=12460")
set_tests_properties(pipe PROPERTIES  TIMEOUT "5")
add_test(platform "/Users/atman/code/pylon/nng/tests/platform" "-v" "-p" "TEST_PORT=12480")
set_tests_properties(platform PROPERTIES  TIMEOUT "5")
add_test(pollfd "/Users/atman/code/pylon/nng/tests/pollfd" "-v" "-p" "TEST_PORT=12500")
set_tests_properties(pollfd PROPERTIES  TIMEOUT "5")
add_test(reconnect "/Users/atman/code/pylon/nng/tests/reconnect" "-v" "-p" "TEST_PORT=12520")
set_tests_properties(reconnect PROPERTIES  TIMEOUT "5")
add_test(resolv "/Users/atman/code/pylon/nng/tests/resolv" "-v" "-p" "TEST_PORT=12540")
set_tests_properties(resolv PROPERTIES  TIMEOUT "10")
add_test(scalability "/Users/atman/code/pylon/nng/tests/scalability" "-v" "-p" "TEST_PORT=12560")
set_tests_properties(scalability PROPERTIES  TIMEOUT "20")
add_test(sha1 "/Users/atman/code/pylon/nng/tests/sha1" "-v" "-p" "TEST_PORT=12580")
set_tests_properties(sha1 PROPERTIES  TIMEOUT "5")
add_test(sock "/Users/atman/code/pylon/nng/tests/sock" "-v" "-p" "TEST_PORT=12600")
set_tests_properties(sock PROPERTIES  TIMEOUT "5")
add_test(synch "/Users/atman/code/pylon/nng/tests/synch" "-v" "-p" "TEST_PORT=12620")
set_tests_properties(synch PROPERTIES  TIMEOUT "5")
add_test(tcp "/Users/atman/code/pylon/nng/tests/tcp" "-v" "-p" "TEST_PORT=12640")
set_tests_properties(tcp PROPERTIES  TIMEOUT "60")
add_test(tcp6 "/Users/atman/code/pylon/nng/tests/tcp6" "-v" "-p" "TEST_PORT=12660")
set_tests_properties(tcp6 PROPERTIES  TIMEOUT "60")
add_test(transport "/Users/atman/code/pylon/nng/tests/transport" "-v" "-p" "TEST_PORT=12680")
set_tests_properties(transport PROPERTIES  TIMEOUT "5")
add_test(udp "/Users/atman/code/pylon/nng/tests/udp" "-v" "-p" "TEST_PORT=12700")
set_tests_properties(udp PROPERTIES  TIMEOUT "5")
add_test(url "/Users/atman/code/pylon/nng/tests/url" "-v" "-p" "TEST_PORT=12720")
set_tests_properties(url PROPERTIES  TIMEOUT "5")
add_test(ws "/Users/atman/code/pylon/nng/tests/ws" "-v" "-p" "TEST_PORT=12740")
set_tests_properties(ws PROPERTIES  TIMEOUT "30")
add_test(bus "/Users/atman/code/pylon/nng/tests/bus" "-v" "-p" "TEST_PORT=12760")
set_tests_properties(bus PROPERTIES  TIMEOUT "5")
add_test(pipeline "/Users/atman/code/pylon/nng/tests/pipeline" "-v" "-p" "TEST_PORT=12780")
set_tests_properties(pipeline PROPERTIES  TIMEOUT "5")
add_test(pair1 "/Users/atman/code/pylon/nng/tests/pair1" "-v" "-p" "TEST_PORT=12800")
set_tests_properties(pair1 PROPERTIES  TIMEOUT "5")
add_test(pubsub "/Users/atman/code/pylon/nng/tests/pubsub" "-v" "-p" "TEST_PORT=12820")
set_tests_properties(pubsub PROPERTIES  TIMEOUT "5")
add_test(reqctx "/Users/atman/code/pylon/nng/tests/reqctx" "-v" "-p" "TEST_PORT=12840")
set_tests_properties(reqctx PROPERTIES  TIMEOUT "5")
add_test(reqpoll "/Users/atman/code/pylon/nng/tests/reqpoll" "-v" "-p" "TEST_PORT=12860")
set_tests_properties(reqpoll PROPERTIES  TIMEOUT "5")
add_test(reqrep "/Users/atman/code/pylon/nng/tests/reqrep" "-v" "-p" "TEST_PORT=12880")
set_tests_properties(reqrep PROPERTIES  TIMEOUT "5")
add_test(reqstress "/Users/atman/code/pylon/nng/tests/reqstress" "-v" "-p" "TEST_PORT=12900")
set_tests_properties(reqstress PROPERTIES  TIMEOUT "60")
add_test(respondpoll "/Users/atman/code/pylon/nng/tests/respondpoll" "-v" "-p" "TEST_PORT=12920")
set_tests_properties(respondpoll PROPERTIES  TIMEOUT "5")
add_test(survey "/Users/atman/code/pylon/nng/tests/survey" "-v" "-p" "TEST_PORT=12940")
set_tests_properties(survey PROPERTIES  TIMEOUT "5")
add_test(surveyctx "/Users/atman/code/pylon/nng/tests/surveyctx" "-v" "-p" "TEST_PORT=12960")
set_tests_properties(surveyctx PROPERTIES  TIMEOUT "5")
add_test(surveypoll "/Users/atman/code/pylon/nng/tests/surveypoll" "-v" "-p" "TEST_PORT=12980")
set_tests_properties(surveypoll PROPERTIES  TIMEOUT "5")
add_test(compat_block "/Users/atman/code/pylon/nng/tests/compat_block" "13000")
set_tests_properties(compat_block PROPERTIES  TIMEOUT "5")
add_test(compat_bug777 "/Users/atman/code/pylon/nng/tests/compat_bug777" "13010")
set_tests_properties(compat_bug777 PROPERTIES  TIMEOUT "5")
add_test(compat_bus "/Users/atman/code/pylon/nng/tests/compat_bus" "13020")
set_tests_properties(compat_bus PROPERTIES  TIMEOUT "5")
add_test(compat_cmsg "/Users/atman/code/pylon/nng/tests/compat_cmsg" "13030")
set_tests_properties(compat_cmsg PROPERTIES  TIMEOUT "5")
add_test(compat_msg "/Users/atman/code/pylon/nng/tests/compat_msg" "13040")
set_tests_properties(compat_msg PROPERTIES  TIMEOUT "5")
add_test(compat_iovec "/Users/atman/code/pylon/nng/tests/compat_iovec" "13050")
set_tests_properties(compat_iovec PROPERTIES  TIMEOUT "5")
add_test(compat_device "/Users/atman/code/pylon/nng/tests/compat_device" "13060")
set_tests_properties(compat_device PROPERTIES  TIMEOUT "5")
add_test(compat_pair "/Users/atman/code/pylon/nng/tests/compat_pair" "13070")
set_tests_properties(compat_pair PROPERTIES  TIMEOUT "5")
add_test(compat_pipeline "/Users/atman/code/pylon/nng/tests/compat_pipeline" "13080")
set_tests_properties(compat_pipeline PROPERTIES  TIMEOUT "5")
add_test(compat_reqrep "/Users/atman/code/pylon/nng/tests/compat_reqrep" "13090")
set_tests_properties(compat_reqrep PROPERTIES  TIMEOUT "5")
add_test(compat_survey "/Users/atman/code/pylon/nng/tests/compat_survey" "13100")
set_tests_properties(compat_survey PROPERTIES  TIMEOUT "5")
add_test(compat_reqttl "/Users/atman/code/pylon/nng/tests/compat_reqttl" "13110")
set_tests_properties(compat_reqttl PROPERTIES  TIMEOUT "5")
add_test(compat_shutdown "/Users/atman/code/pylon/nng/tests/compat_shutdown" "13120")
set_tests_properties(compat_shutdown PROPERTIES  TIMEOUT "5")
add_test(compat_surveyttl "/Users/atman/code/pylon/nng/tests/compat_surveyttl" "13130")
set_tests_properties(compat_surveyttl PROPERTIES  TIMEOUT "5")
add_test(compat_poll "/Users/atman/code/pylon/nng/tests/compat_poll" "13140")
set_tests_properties(compat_poll PROPERTIES  TIMEOUT "5")
add_test(compat_options "/Users/atman/code/pylon/nng/tests/compat_options" "-v" "-p" "TEST_PORT=13150")
set_tests_properties(compat_options PROPERTIES  TIMEOUT "5")
add_test(cplusplus_pair "/Users/atman/code/pylon/nng/tests/cplusplus_pair" "13170")
set_tests_properties(cplusplus_pair PROPERTIES  TIMEOUT "5")
