sudo: required
language: python

matrix:
  include:
    - os: linux
      env: LUA="luajit 2.0"
    - os: linux
      env: LUA="luajit 2.1"
    - os: osx
      language: generic
      env: LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA # install all stuff into ./lua_install
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck
  - luarocks install busted

script:
  - luacheck --std max+busted *.lua
  - busted --verbose . || exit 1
  - if [ "$LUA" = "luajit 2.1" ]; then sudo bash travis.sh; fi
